version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    # enviromnent:
    #   IMAGE_NAME: 
    #   GCR_REPO: 
    #   GCP_PROJECT: 
    #   CLOUDSDK_COMPUTE_ZONE: 
    working_directory: /go/src/github.com/TaxiN/sample-app-ci
    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
      - checkout
      - run:
          name: Authenticate for pushing image to GCR
          command: |
            echo ${GCP_SERVICE_ACCOUNT_KEY} | gcloud auth activate-service-account --key-file=-
            gcloud --quiet auth configure-docker
            gcloud --quiet config set project ${GCP_PROJECT}
            gcloud --quiet config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
      - run:
          name: Build docker image and set image tag
          command: docker build -t ${GCR_REPO}/${IMAGE_NAME}:$CIRCLE_SHA1 .
      # - run:
      #     name: Tag to latest
      #     command: docker tag ${GCR_REPO}/${IMAGE_NAME}:latest ${GCR_REPO}/${IMAGE_NAME}:${CIRCLE_SHA1}
      # - run:
      #     name: Docker login 
      #     command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Push image to repository
          command: docker push ${GCR_REPO}/${IMAGE_NAME}
      - slack/notify:
          color: '#42e2f4'
          message: Message notification
          webhook: ${SLACK_WEBHOOK}
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master